global using System.Runtime.CompilerServices;
global using Ardalis.SharedKernel;
global using NUthreads.Core.ContributorAggregate;
global using NUthreads.UseCases.Contributors.Create;
global using FluentAssertions;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Xunit;
